### ISSUE TITLE
pgrep "$APPNAME" not working

### ISSUE THREAD

**Issue by patrickludwig** [laurent22/rsync-time-backup#107]
First of all big thanks for making this great script available!

The inital backup of my laptop will take many hours. Since the laptop does never run that long, the backup script is started via cron job every (let's say) 15 minutes. I found that after some time several instances of rsync are running.

IMHO line 310 is not working correctly:

`if [ "$RUNNINGPID" = "$(pgrep "$APPNAME")" ]; then`

In order to isolate the problem, I tested the following code under Ubuntu 16.04 and OpenSuSE 12.3. 

```
#!/usr/bin/env bash
# findme.sh

echo $$  # this PID

APPNAME=$(basename $0 | sed "s/\.sh$//")
echo "$APPNAME"

RUNNINGPID=$$    # just to check
RUNNINGPIDNAME=$(ps -p $RUNNINGPID -o cmd= | awk '{print $2}' | sed 's!.*/!!' | sed "s/\.sh$//") 
echo "$RUNNINGPIDNAME"

if [ "$RUNNINGPIDNAME" = "$APPNAME" ]; then
  echo "backup process still running..."
fi

sleep 300
echo "All done!"
```

'pgrep findme' does neither find the APPNAME nor the PID, since 'bash' is the executing program! Solely 'pgrep -f findme' finds the PID. 

Moreover, in the original version there is an issue comparing the PIDs, when two instances of the program with the same APPNAME are running at the same time: The already RUNNINGPID job and the new process. In this case 'pgrep -f' will return two PIDs and the comparison fails.

Instead one should check, as done for cygwin, whether the name of the process currently running under the RUNNINGPID is the same as APPNAME.

**Comment by laurent22** [comment]
I think that should be fixed in #109
