### ISSUE TITLE
if rsyncing on same machine do not use compress 

### ISSUE THREAD

**Issue by zwotzie** [laurent22/rsync-time-backup#142]
In my setup i make a backup on same linux computer to a seperate hard disc. 

So using compress by default is causing huge slow down and waste of cpu. Yes it is easy to delete from the script but a --no-compression flag would be more convenient.

**Comment by felixheidecke** [comment]
Dropping `--compression` on local backups is a night-and-day difference in performance! I fully support @zwotzie on this one.

**Comment by laurent22** [comment]
I think it should be removed by default then, and only added when doing ssh backup.

**Comment by asclepius** [comment]
Yes.  Compression slows things down significantly.  Probably even on local network transfers for those on wired connections.

**Comment by laurent22** [comment]
I can't make the change right now but if someone can create a pull request that removes the option, I'll merge it.

**Comment by filippocarletti** [comment]
The PR may break some scripts.
I expect that "--rsync-get-flags" prints only rsync valid flags, not a phrase/comment.

**Comment by laurent22** [comment]
I agree, I've moved the comment to the help text.

**Comment by laurent22** [comment]
Closed by #159
