### ISSUE TITLE
does not run in cron

### ISSUE THREAD

**Issue by pmkelly53** [laurent22/rsync-time-backup#160]
Runs great from command line.  Will not run when I set up cron.  Searched for answers, nothing works.  
05 05 * * * rsync_tmbackup.sh /home /mnt/0adf69bb-5799-4181-aa8a-3c5e3013f872/rsync_tmbackup

**Comment by kapitainsky** [comment]
What is (if any) logged error? check /var/log/syslog? If you haven't reconfigured anything,the entries will be in there.

**Comment by pmkelly53** [comment]
These are the entries in /var/log/syslog.  Looks like cron worked except that I do not see the backup created.

Aug 17 05:05:01 Debiandesktop2018 CRON[2983]: (patrick) CMD (rsync_tmbackup.sh /home /mnt/0adf69bb-5799-4181-aa8a-3c5e3013f872/rsync_tmbackup)
Aug 17 05:05:01 Debiandesktop2018 CRON[2982]: (CRON) info (No MTA installed, discarding output)
Aug 17 05:17:01 Debiandesktop2018 CRON[3005]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)

**Comment by kapitainsky** [comment]
enable rsync-time-backup logging by adding 
--log-dir "/mnt/0adf69bb-5799-4181-aa8a-3c5e3013f872/rsync_tmbackup/log"

if rsync is run it will log all output where you can see what prevents backup from being created

**Comment by kapitainsky** [comment]
also you can redirect your cron job output to file and see there

`05 05 * * * (rsync_tmbackup.sh /home /mnt/0adf69bb-5799-4181-aa8a-3c5e3013f872/rsync_tmbackup) >> /tmp/rsync.log 2>&1`

**Comment by pmkelly53** [comment]
Here is the result.
/bin/sh: 1: rsync_tmbackup.sh: not found
I have rsync_tmbackup.sh in /usr/local/bin 
I do not see a  /bin/sh 
I sure appreciate your help with this kapitainsky.
This is my first attempt at using cron.

**Comment by kapitainsky** [comment]
use in your cron full path to the script (always good idea)

`05 05 * * *  /usr/local/bin/rsync_tmbackup.sh /home /mnt/0adf69bb-5799-4181-aa8a-3c5e3013f872/rsync_tmbackup`

/usr/local/bin is non on default cron PATH.

you can read more about it for example here 

https://linuxize.com/post/scheduling-cron-jobs-with-crontab/

see Crontab Variables section

**Comment by open-dynaMIX** [comment]
For me it's also not working from cron. Not sure if it's the same issue though.

I'm using cronie on Arch Linux.

Here's the cron output:

```
Aug 18 11:31:01 MYHOST CROND[10612]: (fabio) CMDOUT (rsync_tmbackup: Safety check failed - the destination does not appear to be a backup folder or drive (marker file not found).)
Aug 18 11:31:01 MYHOST CROND[10612]: (fabio) CMDOUT (rsync_tmbackup: If it is indeed a backup folder, you may add the marker file by running the following command:)
Aug 18 11:31:01 MYHOST CROND[10612]: (fabio) CMDOUT (rsync_tmbackup: )
Aug 18 11:31:01 MYHOST CROND[10612]: (fabio) CMDOUT (rsync_tmbackup: ssh -p 22 fabio@BACKUPHOST 'mkdir -p -- "/home/fabio/BACKUPDIR" ; touch "/home/fabio/BACKUPDIR/backup.marker"')
```

All the paths mentioned in the output are correct.

Directly running from CLI works without any issues.

**Comment by open-dynaMIX** [comment]
Sorry, this was an obvious one:

By default I use an ssh key with a passphrase. Of course this key is not automatically unlocked when running ssh from cron. Now I've tested it with a key that has no passphrase and it's working as expected.

The message from rsync_tmbackup is pretty misleading though.

**Comment by pmkelly53** [comment]
It works like it should now.  Thank you again kapitainsky.   I looked at that article at linuxize and it was helpful in explaining the crontab variables.

**Comment by ghost** [comment]
> Sorry, this was an obvious one:
> 
> By default I use an ssh key with a passphrase. Of course this key is not automatically unlocked when running ssh from cron. Now I've tested it with a key that has no passphrase and it's working as expected.
> 
> The message from rsync_tmbackup is pretty misleading though.
> 
> edit: I'm using gnome-keyring as ssh-agent. Adding following line to the script that calls `rsync_tmbackup.sh` allows me to use an ssh key with a passphrase (provided the keyring is unlocked):
> 
> ```shell
> export SSH_AUTH_SOCK="/run/user/$(id -u)/keyring/ssh"
> ```

So I use  an SSH key with *no* passphrase and I still have this problem and this fixed it for me too :) Thank you!
