### ISSUE TITLE
Disk 100% full - which backups can safely be deleted?

### ISSUE THREAD

**Issue by hazelra** [laurent22/rsync-time-backup#241]
I've been using rsync-time for years and my drive is 100% full, however new backups still seem to work which is confusing.
(/dev/mapper/2tbdsk 1922726704 - 1916233748   -  0 - 100%   -   /2tbdsk) 
Some old backups were deleted, but the disk still shows 100% full, and there are no errors for new backups. I'm trying to understand which backups are safe to delete and how the script deals with a full drive.

Since each backup is linked to the previous backups are any safe to delete? 

Which backups can be deleted?

Will the script keep the disk at 100% full?

Why are backups still working?

Thank you for the help

**Comment by superman-lopez** [comment]
The script will check if there is insufficient space, and (unless disabled by you) it will expire older backups to free up space.

The script uses hard links to create incremental backups: this means you can delete any backup and the remaining backups will continue to be functional.

**Comment by hazelra** [comment]
Thank you!!

**Comment by superman-lopez** [comment]
You are welcome.  If possible, please close the issue.
