### ISSUE TITLE
No backup marker issue

### ISSUE THREAD

**Issue by PrzemekSkw** [laurent22/rsync-time-backup#254]
Hello, I do everything like installation guide and have that error:
```
dietpi@DietPi:~/rsync-backup/rsync-time-backup$ ./rsync_tmbackup.sh /home /mnt/Toshiba
rsync_tmbackup: Safety check failed - the destination does not appear to be a backup folder or drive (marker file not found).
rsync_tmbackup: If it is indeed a backup folder, you may add the marker file by running the following command:
rsync_tmbackup: 
rsync_tmbackup: mkdir -p -- "/mnt/Toshiba" ; touch "/mnt/Toshiba/backup.marker"
rsync_tmbackup: 
dietpi@DietPi:~/rsync-backup/rsync-time-backup$ 
```
Regards.

**Comment by psmanek** [comment]
Do as it is written. "backup.marker" file is missing.

mkdir -p -- "/mnt/Toshiba" ; touch "/mnt/Toshiba/backup.marker"

**Comment by PrzemekSkw** [comment]
Thanks, that works. It should mentioned be on main site in installation section but I have problem with that folder it make: `latest....`
I want to make backups from other devices so I need to make clean folders structure like `/mnt/Toshiba/Backups/miniPC` and `/mnt/Toshiba/Backups/raspberry`.
How to do that with that marker command?
