### ISSUE TITLE
A new Python port of `rsync-time-backup` that is fully tested: `rsync-time-machine.py`

### ISSUE THREAD

**Issue by basnijholt** [laurent22/rsync-time-backup#258]
@laurent22, thank you so much for developing this code, I have been a happy user for some years!

I noticed that there have been concerns about the maintenance status of `rsync-time-backup`. To address these concerns, I've developed [`rsync-time-machine.py`](https://github.com/basnijholt/rsync-time-machine.py), a Python port of the `rsync-time-backup` script. This newly released package offers the same functionality as the original, but with a few additional enhancements.

[`rsync-time-machine.py`](https://github.com/basnijholt/rsync-time-machine.py) provides Time Machine-style backups using rsync, with full compatibility with the original `rsync-time-backup`. It works on Linux, macOS, and Windows (via WSL or Cygwin), and it creates incremental backups of files and directories to the destination of your choice.

The advantages of this new tool are:

- No external dependencies (only Python ≥3.7)
- Pretty terminal output and fully typed code
- Fully tested
- Allow to use ssh config directly (no need for [user]@[host] pattern)

You can find the new package at [rsync-time-machine.py](https://github.com/basnijholt/rsync-time-machine.py). The detailed README and examples can help you get started with the transition.

[`rsync-time-machine.py`](https://github.com/basnijholt/rsync-time-machine.py) might be a worthy alternative to `rsync-time-backup` to those folks that like Python 🐍

**Comment by laurent22** [comment]
Ok thanks for creating this
