### ISSUE TITLE
improvements and new features

### ISSUE THREAD

**Issue by eaut** [laurent22/rsync-time-backup#38]
Hi Laurent,

I made significant contributions to my fork of your script. Everything is still backwards compatible with existing backup archives.
Now I am wondering if you are interested to go this direction with your version? List of main changes below, see https://github.com/eaut/rsync-time-backup for all details.

MAIN IMPROVEMENTS AND NEW FEATURES

- more priority for new backups:
  1. expire backups by moving them to an expired folder (fast!)
  2. create new backup
  3. delete old backups thereafter (slow!, all inodes have to be removed)
- shorter backup times:
  - minimize inode deletions/creations by reusing expired backups - usually most files/inodes have not changed even compared to older backups
- backup.marker file can be used as config file
  - more flexible and configurable backup expiration windows
  - UTC & local time handling as part of backup.marker config
- flexible command line interface, new subcommands and options
  - compare two backups, initialize backup marker, ...
  - option to log to syslog

**Comment by laurent22** [comment]
Thanks for the suggestions, I will have a look at the code and see if some of the features can be imported.
