### ISSUE TITLE
find: No match. using ssh

### ISSUE THREAD

**Issue by lorentrogers** [laurent22/rsync-time-backup#41]
I'm trying to run backups to a local NAS over SSH, but for some reason it's not finding the last backup. To seed the backup, I mounted the destination and ran the script as local. That succeeded, but now when I try to tun it on the same destination as SSH, I get:

    find: No match.
    rsync_tmbackup: No previous backup - creating new one.

At this point, I `ctrl+c` to kill it, since it would just re-upload all the files I'd just seeded. What's the best way to do this?

**Comment by fustundag** [comment]
On local NAS, can your run cmd : 

find "$DEST_FOLDER" -type d -name "????-??-??-??????" -prune | sort -r

$DEST_FOLDER is your local backup folder at NAS

**Comment by lorentrogers** [comment]
Yes, when I have my NAS destination mounted, it finds the previous backups. (That is, I have `/mnt/lorentrogers/backups` mounted to my nas: `lorentrogers@xxx.xxx.xxx.xxx:backups`)

Also, thanks for the super fast reply!

**Comment by fustundag** [comment]
You should give absolute path on NAS. it should be like this if your bakcups dir at root of NAS:

/bin/bash ./rsync_tmbackup.sh ./ lorentrogers@xxx.xxx.xxx.xxx:**/backups** ./backup_ignore

**Comment by lorentrogers** [comment]
Hmm. Both absolute and relative paths seem to be working, but the folders still aren't being found... When I try a destination folder without the `backup.marker` file, it correctly throws an error. But with both relative and absolute paths, it gives `find: No match`.

Also, for what it's worth, the destination folder is under `/mnt/Vault/home/lorentrogers/backups/computername`. The NAS is built with FreeNAS (FreeBSD).

**Comment by laurent22** [comment]
Could you maybe add some `echo` commands near the find calls, to double-check which `find` command is failing? I guess we should also fix this error message because `find: No match` doesn't tell how to fix the problem.

**Comment by lorentrogers** [comment]
Re-reading your original comment, I realize I never actually tried what you suggested.

Running this command works just fine:

    find /mnt/lorentrogers/backup/thinkpad-x201 -type d -name "????-??-??-??????" -prune | sort -r

It gives the list of previous backups. But, 

    find lorentrogers@xxx.xxx.xxx.xxx:/mnt/Vault/home/lorentrogers/backup/thinkpad-x201 -type d -name "????-??-??-??????" -prune | sort -r

returns: 

    find: `lorentrogers@xxx.xxx.xxx.xxx:/mnt/Vault/home/lorentrogers/backup/thinkpad-x201': No such file or directory

Could this be because the `find` function doesn't support remote destinations?

**Comment by lorentrogers** [comment]
@laurent22 Agreed, this should probably have a better error attached. 

After some experimentation, it looks like `fn_find_backups()` is being called on a local path, rather than the remote one. (That is, `$DEST_FOLDER` is set to `backup/test` rather than `lorentrogers@xxx.xxx.xxx.xxx:backup/test`.)

Seems like `$DEST_FOLDER` isn't being properly set for some reason. I'll do some more investigation on this.

**Comment by lorentrogers** [comment]
Aah -- I think I've found it. 

@laurent22 Agreed, this should probably have a better error attached. 

After some experimentation, it looks like `fn_find_backups()` is being called on a local path, rather than the remote one. That is, `$DEST_FOLDER` is set to `backup/test`, which looks for this on the local machine. This will fail each time, since it's not looking at the right computer. (Unless there happens to be a folder there on the local machine, in which case this could be a major problem.)

Since `find` doesn't seem to support remote calls, it seems like we're going to need another way of checking these folders.

**Comment by fustundag** [comment]
fn_find_backups() calls "find" cmd using fn_run_cmd. "fn_run_cmd" checks if target ssh, runs cmd on remote. 

You shoudl check remote find like this : 

ssh lorentrogers@xxx.xxx.xxx.xxx 'find /mnt/Vault/home/lorentrogers/backup/thinkpad-x201 -type d -name "????-??-??-??????" -prune | sort -r'

**Comment by lorentrogers** [comment]
Hmm, you're right. Perhaps the issue is with the double quotes / single quotes in the eval statement? When I look at what's being run in `fn_run_cmd`, I see that we loose the double quotes around "????-??-??-??????". Running the function alone confirms that this is the issue. 

This succeeds: 

    ssh lorentrogers@xxx.xxx.xxx.xxx 'find /mnt/Vault/home/lorentrogers/backup/test -type d -name "????-??-??-??????" -prune | sort -r'

This fails:

    ssh lorentrogers@xxx.xxx.xxx.xxx 'find /mnt/Vault/home/lorentrogers/backup/test -type d -name ????-??-??-?????? -prune | sort -r'

**Comment by lorentrogers** [comment]
I'll put together a pull request with the quotes escaped, since that seems to fix it.

**Comment by laurent22** [comment]
PR: https://github.com/laurent22/rsync-time-backup/pull/42
