### ISSUE TITLE
manual version pruning

### ISSUE THREAD

**Issue by hughc** [laurent22/rsync-time-backup#43]
I'm struggling with disk space in some cases, and periodic manual pruning is necessary to keep backups working.

After reading up on how hard links work under *nix (ie that all files are really hardlinks, and an inode will be freed only when its hardlink count reaches zero) is it right to say that any given backup directory can be deleted without affecting other backups?

Is it correct that all that would actually be deleted would be hardlinks to inodes where the link being deleted was the last link? ie a file that had subsequently been deleted (and so no longer appeared in the backup) or was updated, in which case the earlier version would be 'deleteable'. 

Thanks for the script, I'm using it with minimal modifications under busybox on a Synology NAS.

**Comment by laurent22** [comment]
Yes this is correct, each backup set is completely independent. It can be copied or deleted without affecting any of the other backup sets. The script actually occasionally removes the oldest backup sets and it simply done with an `rm` command.
