### ISSUE TITLE
Handle SSH port other than 22.

### ISSUE THREAD

**Issue by nowindows** [laurent22/rsync-time-backup#45]
How does one handle a non standard SSH port?

**Comment by laurent22** [comment]
Good question, and based on the current code it doesn't look like it's supported. Perhaps @fustundag could confirm?

**Comment by fustundag** [comment]
Yes, no support for custom port. We should add.

**Comment by laurent22** [comment]
Ok, tagging this as a feature request.

**Comment by laurent22** [comment]
Fixed in 6157826651f0cbd685f8652ba4967a6b4ed58b99
