### ISSUE TITLE
ssh?

### ISSUE THREAD

**Issue by djquazzi** [laurent22/rsync-time-backup#48]
This script is amazing. Thank you so much...
My only question is to run this over a ssh session to a remote machine.
Is there an easy way?

Something like this?

> sudo ./rsync_tmbackup.sh /Volumes/Data/ USER@197.12.1.1:~/mac_backup/

Above does work, but it prompts for the remote machines password several times.

**Comment by musically-ut** [comment]
I was running into similar problems and had made manual changes to this script on my local machine to use custom identity files per server. However, later I moved to [eaut/rsync-time-backup](https://github.com/eaut/rsync-time-backup) and I was able to use the `--ssh-opt` argument to "select" the right identity file for each server I ran the script on.

Hope that helps.

**Comment by laurent22** [comment]
To avoid inputting a password, you indeed need to use public key authentication, for example as described [there](https://kb.iu.edu/d/aews). We don't propose a special solution for this since this is a feature of SSH.

**Comment by djquazzi** [comment]
100% correct. Works like a charm. Thank you
