### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by Plasma-000** [laurent22/rsync-time-backup#49]
Could you please add the option/flag to print out a progress bar or something after each file copy to get some sense of where it is in the process?

**Comment by laurent22** [comment]
Looks like that can be done using the `--info=progress2` option ([ref](http://www.cyberciti.biz/faq/show-progress-during-file-transfer/)). But that needs to be investigated since I've never heard of this option so I don't know how well supported it is.

**Comment by Plasma-000** [comment]
Didn't know about that. I'll have a try, thanks.
