### ISSUE TITLE
marker file not being recognised

### ISSUE THREAD

**Issue by Plasma-000** [laurent22/rsync-time-backup#50]
I just updated to the latest version and it appears that my marker files is being totally ignored, and even when I run the command to create a new marker file, it is not recognising it.

(OSX 10.11.4)

(Note: It gives me the warning saying "Safety check failed - the destination does not appear to be a backup folder or drive (marker file not found)." and prints the command for generating a marker file)

**Comment by Plasma-000** [comment]
Can this problem be reproduced? Is there any plan to fix it?

**Comment by laurent22** [comment]
When you run the commands to create the marker file, is that file really created?

Could you run `ll /path/to/marker` to see what are its permissions?

**Comment by Plasma-000** [comment]
Yes, the file gets created with permissions -rw-r--r--

**Comment by laurent22** [comment]
I cannot replicate this issue. If it happens again, please reopen the issue.

**Comment by Plasma-000** [comment]
I am reopening this issue because it seems that this problem still exists...

I am now running the MacOS Sierra public build 16A313a. Marker file is still not detected 

When I try running the Shell script:

`sudo /Volumes/Backup/rsync_tmbackup.sh /Volumes/Macintosh\ HD /Volumes/Backup/Computer\ Backup/ /Volumes/Backup/exclude.txt`

it gives me:

`rsync_tmbackup: Safety check failed - the destination does not appear to be a backup folder or drive (marker file not found).
rsync_tmbackup: If it is indeed a backup folder, you may add the marker file by running the following command:
rsync_tmbackup: 
rsync_tmbackup: mkdir -p -- "/Volumes/Backup/Computer Backup" ; touch "/Volumes/Backup/Computer Backup/backup.marker"
`

**Comment by laurent22** [comment]
This is quite a confusing issue, based on your previous comment the marker file exists, but `find` cannot find it.

Could you try to run these commands and post the output here?

    ls -la "/Volumes/Backup/Computer Backup/backup.marker"
    find "/Volumes/Backup/Computer Backup/backup.marker"

**Comment by laurent22** [comment]
Now that I look at it more closely, I see that in the `fn_find` function there is no quotes around "$1", which could be the reason why it doesn't work with paths with spaces:

```
fn_find() {
	fn_run_cmd "find $1"  2>/dev/null
}

**Comment by Plasma-000** [comment]
find could find the file easy, and ls returned the same permissions as before.

I hope this is the issue :P

**Comment by Plasma-000** [comment]
Also note that both the script, and the distinction directory are on an external hard drive (not sure if that helps)

**Comment by jozip** [comment]
I have this problem too, but it manifests itself only when it's a cron job and only over ssh. (It works as expected when run in a terminal session.) Spontaneously, I think it fails due to the fact that ssh require information that isn't available in the sub-shell. (Keys?)

**Comment by jozip** [comment]
@Plasma-000, where do you typically run your command? Cron?

**Comment by laurent22** [comment]
Ok the issue with paths that contain path should be fixed in 56a3a89866cc3914f429c1ca1e328a34cb6fcc29
If not, please re-open the issue.
@jozip , regarding ssh-agent, please create a new issue.

**Comment by davidgatti** [comment]
Sorry but I'm running in the same issue. I just created a new server where to store my backups over Ssh. This is a completely fresh system if I use `find` I get this:

```
.
./.bash_logout
./.bash_profile
./.bashrc
./.ssh
./.ssh/authorized_keys
./ssd_data
./ssd_data/Backups
./ssd_data/Backups/macOS
./ssd_data/Backups/macOS/backup.marker
./ssd_data/lost+found
find: ‘./ssd_data/lost+found’: Permission denied
./.bash_history
```

The system there is AWS Linux 2

**Comment by ghost** [comment]
> I have this problem too, but it manifests itself only when it's a cron job and only over ssh. (It works as expected when run in a terminal session.) Spontaneously, I think it fails due to the fact that ssh require information that isn't available in the sub-shell. (Keys?)
> 
> Edit: Yeah, this is exactly what's going on. The sub-shells spawned from the cron daemon have no way of talking to the ssh-agent, even though it's acting on a user's behalf. (There are numerous behaviors and solutions to this problem, way more than what is reasonable to cover in the script.) What I reported is then not a bug, but I think it may be a good idea to add a caveat section to the readme.

Hi,

Have you ever found a solution to this? I can't schedule the script wit cron to run over SSH. I get the same "marker not recognized" error. But it runs fine if I run it from command line. Thanks.

**Comment by laurent22** [comment]
> Hi,
> 
> Have you ever found a solution to this? I can't schedule the script wit cron to run over SSH. I get the same "marker not recognized" error. But it runs fine if I run it from command line. Thanks.

Maybe try to make the script print where it's looking the maker for? It should be the file "backup.marker" and maybe it's looking for it in the wrong place, and you could then adjust the path

**Comment by ghost** [comment]
> > Hi,
> > Have you ever found a solution to this? I can't schedule the script wit cron to run over SSH. I get the same "marker not recognized" error. But it runs fine if I run it from command line. Thanks.
> 
> Maybe try to make the script print where it's looking the maker for? It should be the file "backup.marker" and maybe it's looking for it in the wrong place, and you could then adjust the path

I found a solution elsewhere: This needs to be added to the script that calls rsync_tmbackup.sh:

export SSH_AUTH_SOCK="/run/user/$(id -u)/keyring/ssh"

I don't understand this, but this is something about cron not being able to pass the SSH key, or something like that.
