### ISSUE TITLE
SSH keep asking for password

### ISSUE THREAD

**Issue by psmanek** [laurent22/rsync-time-backup#51]
Hello, is there any way to add password file to command line or something like that? When executed every line of script asks for password.

**Comment by laurent22** [comment]
Hello, to achieve this, the recommended way is to use public key authentication, for example as described [there](https://kb.iu.edu/d/aews). We don't propose a special solution for this since this is a feature of SSH. In general it is simpler and more secure anyway to use public key authentication.
