### ISSUE TITLE
Enhancement: Speed up expire_backup

### ISSUE THREAD

**Issue by nowindows** [laurent22/rsync-time-backup#55]
Great utility!

I have found that expiring backups takes a long time. See: http://www.slashroot.in/which-is-the-fastest-method-to-delete-files-in-linux.

Using either of following (in place of rm -rf -- "$1") should speed things up:

mkdir /tmp/blankdirectory
rsync -a --delete /tmp/blankdirectory/ "$1"

or
cd "$1"
perl -e 'for(<*>){((stat)[9]<(unlink))}'

**Comment by laurent22** [comment]
Yes that would be a good idea. We cannot have a dependency to perl though, but the rsync method would be fine. If someone's interested and can propose a pull request, I'll merge it.

**Comment by joekerna** [comment]
I would create a pull request. Am I right to believe, that `rsync -a --delete /tmp/blankdirectory/ "$1"` does not delete the directory _$1_ itself?

So the full code would be
`mkdir /tmp/blankdirectory`
`rsync -a --delete /tmp/blankdirectory/ "$1"`
`rm -r /tmp/blankdirectory $1`

I'm new to github. Is it the correct approach to create a new branch for the pull-request or should I use one of the existing branches?

**Comment by jamietanna** [comment]
@joekerna if you fork the repo, then on the new repo create a new branch for your changes. Then raise a Pull Request from that branch to this repo.

**Comment by laurent22** [comment]
Also please check that the code works on both local and remote (via the ssh options).

**Comment by laurent22** [comment]
Fixed in https://github.com/laurent22/rsync-time-backup/pull/71
