### ISSUE TITLE
Problems when running backups over ssh in cron

### ISSUE THREAD

**Issue by jozip** [laurent22/rsync-time-backup#56]
This isn't really a bug as such and more of a general caveat. I've had problems with getting backups through to an external site over SSH when the script is run as a cron job. Running in the terminal works fine, which makes it obvious that there's an issue with the cron sub-shell somehow not getting the environment data that it need.

The problem is that there are numerous facets to the problem. Here's three that I've come across:
1, there's no way of talking to a running ssh-agent (since the process is typically started way after the cron daemon, you can't pass an environment variable with a PID),
2, if the ssh-agent is started in the sub-shell, it may still fail due to,
3, keys with password protection fails since the ssh client is run in an non-interactive shell.

So, what can be done? As I mentioned, it's a rat's nest to get this working across all systems, so I'd say that this should be a caveat section in the readme. Some have had success with the `keyring`-package from Gentoo. Some have no problems at all, since the system keyring manages everything as expected (OS X does this well, apparently). Personally, I generated a passwordless key-pair that I use for the backup-machine only. (In my use-case it makes sense, though I wouldn't recommend it.)

**Comment by mackdata** [comment]
I had the same problem.  Adding the following line did solve it for on OSX Yosemite. [Also see Chris Hardie's blog here](https://chrishardie.com/2015/04/cron-rsync-encrypted-ssh-keys-osx/). 
```
# Where ssh-agent is running, for password-less access to the key
export SSH_AUTH_SOCK=$( ls /private/tmp/com.apple.launchd.*/Listeners )
```

**Comment by laurent22** [comment]
Ok since it's a general problem with cron scripts not having direct access to MacOS keyring, it's not something we can't fix on the script.

However a note on the readme file would indeed make sense. I guess we could mention @mackdata's fix along with a link to Chris Hardie's blog.

**Comment by jozip** [comment]
I should've mentioned that I have this problem on my Debian-machine, so it's certainly not restricted to Mac OS. I'd like to add the guide to [keychain](https://wiki.gentoo.org/wiki/Keychain) as a possible fix, along with the passwordless key setup.
