### ISSUE TITLE
Include multiple source folders

### ISSUE THREAD

**Issue by luwes** [laurent22/rsync-time-backup#58]
Is it possible to include multiple source folders?
My command looks a bit like this

```
./rsync-time-backup/rsync_tmbackup.sh \
	~/ \
	"/Volumes/LaCie/Rsync Backups" \
	excluded_patterns.txt
```

and the `excluded_patterns.txt`

```
- /**/
+ /Sites/***
+ /Documents/***
+ /Pictures/***
- *~
- .DS_Store
- .localized
- .sass-cache
- bower_components
- desktop.ini
- node_modules
- Thumbs.db
- ~*
```

but that's not really working like I expected.

**Comment by laurent22** [comment]
I think it can be solved using custom rsync flags via the new `--rsync-set-flags` argument (Please see readme file) for example using custom `--include` and `--include-from` arguments. If that doesn't work, please reopen the issue.
