### ISSUE TITLE
Cannot backup from /

### ISSUE THREAD

**Issue by johnmlang** [laurent22/rsync-time-backup#59]
I'm running Debian 8.0 and I am trying to backup my entire filesystem minus the directories listed in my excludes file.  Regardless of the other arguments I specify, when I set the source to `/`, I get the usage and help text.  The script works wonderfully when I specify another source.

Thanks.

**Comment by laurent22** [comment]
There was indeed an issue when the source path was set to a single "/". We were stripping the last slash which means the script was detecting this argument as empty. It should now be fixed in the last version.

**Comment by johnmlang** [comment]
Thanks for the fix.
