### ISSUE TITLE
location of a log files

### ISSUE THREAD

**Issue by psmanek** [laurent22/rsync-time-backup#60]
Hi,

it would be very useful to change log files location. I'm running script from en external drive but log files are always saved to user home dir.

Thanks,
psman

**Comment by rumski20** [comment]
+1

**Comment by laurent22** [comment]
It's now possible to set the log file directory via the `--log-dir` option. See f9205f6e20adffc595c245fb7e907caa0c13433c

**Comment by rumski20** [comment]
Thanks for the follow-up and continued development. This is a great script.

________________________________
