### ISSUE TITLE
line 55 not work on zsh

### ISSUE THREAD

**Issue by abkrim** [laurent22/rsync-time-backup#61]
this not work 
```
fn_run_cmd "find "$DEST_FOLDER" -type d -name "????-??-??-??????" -prune | sort -r"

zsh:1: no matches found: ????-??-??-??????
```

Must be on zsh
```
fn_run_cmd "find "$DEST_FOLDER" -type d -name \"????-??-??-??????\" -prune | sort -r"
```

**Comment by laurent22** [comment]
That looks right, please could you send it as a pull request?

**Comment by abkrim** [comment]
Hi
I like upload a pull request, but forbidden (403)

1. Download your project
2. Create a locate branch  `git checkout -b zsh-fn_run_cmd`
```
[zsh-fn_run_cmd f8e03a9] scape for zsh shell
 1 file changed, 1 insertion(+), 1 deletion(-)    
```

3. `git add --all `
4. `git commit -m "scape for zsh shell"`
5. `git push -u origin zsh-fn_run_cmd `
```
Username for 'https://github.com': abkrim
Password for 'https://abkrim@github.com': 
remote: Permission to laurent22/rsync-time-backup.git denied to abkrim.
fatal: unable to access 'https://github.com/laurent22/rsync-time-backup.git/': The requested URL returned error: 403     
```

**Comment by musically-ut** [comment]
Hi @abkrim,

The PR workflow on Github is slightly different from sending PRs via mailing list, etc.. 
You first need to fork the repository _within_ Github to your account by using the `Fork` button on the top right. You will need to push your changes (in a new branch as you have done) to your own fork of this repository and then create a PR following the guidelines here: https://help.github.com/articles/creating-a-pull-request/

Hope that helps.
 
PS: Thanks for the PR; I too use zsh, but haven't hit this particular code branch yet.

**Comment by laurent22** [comment]
We use quotes within quotes quite a lot in the script, so I think a PR for this should take care of all these in one go. It seems Bash handles this fine, but apparently not zsh. If someone is familiar with this shell, can do the changes and test, I can merge it.
