### ISSUE TITLE
Purging backups beyond N months

### ISSUE THREAD

**Issue by fthiery** [laurent22/rsync-time-backup#63]
Hi there,

Nice utility ! Only missing thing for me would be great to be able to define a maximum delay after which backups should be purged (e.g. do not keep stuff older than 6 months).

How would you implement that ? Or do you rather recommend a manual purging when target is nearly full ?

**Comment by laurent22** [comment]
Currently it's setup so that old backups are deleted when the target is full. I think that works well most of the time. To customise this, maybe some parameters could be added to tweak the expiration logic.

**Comment by fthiery** [comment]
Okay, i didn't see this, you might want to add a little line on the Readme then ! That's an undocumented (great) feature :)

Also, explicitly explaining in the doc that you can remove any of the old backup folders without worrying might be good as well.

**Comment by laurent22** [comment]
Good point, there's indeed nothing about the expiration logic - I'll add a few lines about it.

**Comment by laurent22** [comment]
Done in d65cb504ccd9c0474a48a0bb5dfbba96124d797a

**Comment by roelvanduijnhoven** [comment]
@laurent22 @fthiery I use this script for some time: loving it! The AVG made me revisit our usage of it however. I would like to guarantee that no backup lives beyond X months. This is not possible as far as I can tell from reading the docs. 

@laurent22 Would a PR adding an expiration options setting the maximum number of months be considered for merge? Any clue as to how I could implement this?

**Comment by laurent22** [comment]
Can you use the expiration strategy from [this branch](https://github.com/laurent22/rsync-time-backup/tree/expiration-strategy) and set a high number for the last parameter?

**Comment by roelvanduijnhoven** [comment]
@laurent22 So you mean something like:

`--strategy "1:1 30:9999999"`

I am not 100% sure on what the semantics would yield. My hope would be that it would only store data that is max 30 days old. And because day 9999999 never comes; the backup won't be generated. But it could also mean that there is single backup that can be up to (9999999 - 1) days old? If the former is the case: we can easily update the PRs readme text :).

A slight change in the semantics could be to use a dash to represent *never*, as in:

`--strategy "1:1 30:-"`

Thanks @laurent22

**Comment by laurent22** [comment]
Right, there's indeed no proper way to keep no backup after a certain time. I would consider for merge the kind of option your describe. If there a token more meaningful than a dash we could use? Maybe `x` or `d`, to show everything after that day is deleted?

**Comment by roelvanduijnhoven** [comment]
Allright @laurent22 I'll have a look at it later this month. The `x` is indeed an improvement over the dash :).

What is the state of the branch? Are there other efforts required to merge it; curious to why is not merged yet :)?

**Comment by laurent22** [comment]
Till today I forgot it wasn't actually merged. It's done now :-)

**Comment by fthiery** [comment]
Thanks for the feature (for reference here is the pr: https://github.com/laurent22/rsync-time-backup/commit/5e0f3bb09dc76a22d7ca089b5ef9b1b9cb7caeb9) !

Is the "x" strategy supported (documentation does not indicate it)?

```
--strategy "1:1 30:x" ?
```

**Comment by laurent22** [comment]
@fthiery, it's not implemented yet. Not sure if @roelvanduijnhoven started looking at it?

**Comment by roelvanduijnhoven** [comment]
@fthiery @laurent22 Still planning to do so. Will do this once we start working at our company at GDPR parts related to mailsystem (for which we backup this way): should be within the next month.
