### ISSUE TITLE
Maintain backup retention by days

### ISSUE THREAD

**Issue by wsokc** [laurent22/rsync-time-backup#65]
I know the backup will delete some old data once the disk full.
The problem I need to maintain some backup retention time, eg: keep the backup only for the last 10 days.
Right now I do deletion manually via other scripts.

Hope can be integrated.

**Comment by joekerna** [comment]
Is this the same as #63 ?

**Comment by wsokc** [comment]
In someway the scripts will clear when the disk about to full which is very nice and smart function.
but on my machine I have Nas centralized to store the backup from several sources which I need to maintain the retention.
It would be nice if we could define our-self how many days of backup we would like to cycle and keep.

**Comment by laurent22** [comment]
Yes at the moment the rules are hardcoded to be similar to those of Time Machine (of MacOS).

It's one of those things were different people will have different needs, so only an option to set the the number of days might not be enough. I guess we'd need something more generic to specify custom expiration rules, but not sure how to implement this without making the script a lot more complicated.

**Comment by wsokc** [comment]
Yes, for now I used external script to do this function.
I'd like the approach simple and easy script.
