### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by mackdata** [laurent22/rsync-time-backup#66]
@laurent22 
I have been using your script for a long time and it has worked extremely well. Thank you for all your hard work.  I'm not that experience with the shell. So when I discovered your script, I had to learn things. I discovered that "flock" is a really nice way to schedule the rsync-tm-backup script, since it helps you to prevent duplicated instances. In my crontab, I have:

```
0	18	*	*	*  /usr/local/bin/flock -n /tmp/rsync_remot.lockfile sh -c 'sh cronstarter "remote" >> ~/.tmp/remote.log' > /dev/null 2>&1
```
Flock, was very important in my case. I sometimes ran into the problem that my current backup was still in process, and crontab wanted to start another instance. With flock, I'm sure that I never get 2 instances of the script.

If you agree, I'd suggest we add a reference to [flock](https://github.com/discoteq/flock) in the documentation.

**Comment by laurent22** [comment]
Yes that's a good point, I guess the script should only ever be used with a lock. Feel free to create the pull request and I'll merge it.

**Comment by laurent22** [comment]
Fixed in https://github.com/laurent22/rsync-time-backup/pull/69
