### ISSUE TITLE
hard links on mac

### ISSUE THREAD

**Issue by vejer** [laurent22/rsync-time-backup#67]
Dear community,

I'm trying to figure out this excellent script. However on my mac all backup folders take the full size of the original folder even if almost nothing was changed in the original folder. I've been googling on hard links on a mac which confused me. So I was wondering how people are running the rsync-time-backup script on their macs.  

Many thanks

**Comment by joekerna** [comment]
How are you determining the size of the backup folders?
Let's say your backup is 1 GB. Then every backup-folder will take 1 GB of space if you look at it individually. 
But if you take 10 backups of the same data (nothing has ever changed), you will see 10 folders of 1 GB each, but the total size of the entire backup directory will still only be 1 GB (not 10 x 1 GB = 10 GB).

**Comment by laurent22** [comment]
Yes that's pretty much it. There's also the overhead of the FAT so even if nothing is changed each new backup might still take some extra space anyway.
