### ISSUE TITLE
Script seems to ignore .txt file

### ISSUE THREAD

**Issue by asaivan** [laurent22/rsync-time-backup#68]
Hi, I ran a test on this, and it seems to sync great, except that it left  out a .txt file from the dir I was syncing.  Do you know why this would be?

Thanks.

**Comment by musically-ut** [comment]
Was the file explicitly excluded? Or was it created after the backup was started?

**Comment by asaivan** [comment]
No it wasn't, but I'm beginning to suspect permissions errors, let me get back to you.  Thanks for getting back so quick.

**Comment by laurent22** [comment]
Could indeed be a permission issue. If it happens again please reopen the issue.
