### ISSUE TITLE
Remove old backups after new one has completed successfully

### ISSUE THREAD

**Issue by joekerna** [laurent22/rsync-time-backup#70]
I think the script should until the new backup has been completed successfully before removing previous backups.
In case the new backup gets interrupted or fails the user would lose one of the previous backups without creating a new one.

PS: What happens if a backups processes is interrupted after for example 50%. Will it be deleted to ensure the integrity or will the next backup be run incrementally on the 50%-backup?

**Comment by laurent22** [comment]
> PS: What happens if a backups processes is interrupted after for example 50%. Will it be deleted to ensure the integrity or will the next backup be run incrementally on the 50%-backup?

It will resume from that 50% backup next time

> I think the script should until the new backup has been completed successfully before removing previous backups.
> In case the new backup gets interrupted or fails the user would lose one of the previous backups without creating a new one.

The script is designed to only delete the old backups so even if the new one is interrupted there will still be a recent one available.

There's no perfect solution I think:
- if we delete backups after, then we might run out of space while the new backup is running, and will have to delete backups anyway.
- If we delete before, there's indeed this problem of deleting and then having the new backups to fail.

However between both options, I'd rather leave it as it is as there's not really a risk of accidental data loss.

**Comment by joekerna** [comment]
I didn't know it would resume from that 50%... I think that's pretty cool!

Thanks for the fast response and the script of course!
