### ISSUE TITLE
Keep logfiles as long as backup is present

### ISSUE THREAD

**Issue by joekerna** [laurent22/rsync-time-backup#73]
I would like to keep the logfiles past a successful backup run. I want to grep them to retrieve some information which I will later send to [Terminal Notifier](https://github.com/julienXX/terminal-notifier).

Should we add an option like `--keep-logfile` that keeps the logfiles of all backups that are still present. Once the backups are deleted, the logfiles should also be deleted.

**Comment by laurent22** [comment]
The log file we generate is currently is for internal application-specific things like checking if there was an error during copying. I feel that adding more logic to it would be out of scope of this project since everyone might have different requirement with what they want to do with the logs.

However we output everything so it's always possible to capture the log using regular Bash redirection `>` and then doing any custom processing on them.

**Comment by joekerna** [comment]
I understand!
I'm looking for the amount of data that was actually tranferred by rsync. Could I pipe the output and retrieve that information?
`rsync-time-backup ........ | grep `

**Comment by joekerna** [comment]
Or would you be interested in including an optional feature that presents notifications using `notify-send` on KDE/Gnome or `terminal-notifier` on Mac OSX?
I think it's pretty neat to have a decent notification whenever the script has run through a cronjob.

**Comment by laurent22** [comment]
I'm not really familiar with these tools. Can't the output of the script simply be piped into these programs to create custom notifications?

**Comment by laurent22** [comment]
I've now added the option to set the log directory via the `--log-dir` option. When it's used, the log files also aren't managed by the script anymore, so aren't deleted automatically (See f9205f6e20adffc595c245fb7e907caa0c13433c for more information).

**Comment by joekerna** [comment]
That great for me. I'll add the `--stats -h` option to `rsync` myself. I think that provides an important piece of information (amount of data actually transferred). If you agree you can add it to the standard set of parameters to improve information in the logfile.

**Comment by joekerna** [comment]
Thanks.. this makes my script a little slimmer
