### ISSUE TITLE
fn_rm requires /tmp to exist

### ISSUE THREAD

**Issue by joekerna** [laurent22/rsync-time-backup#77]
When I modified the fn_rm function with pull-request @ #71 I assumed that the directory `/tmp` exists and that the user may create a directory there.
Is this something we can assume? I've never seen a system where this is not the case but if that directory doesn't exist `fn_rm` would fail.
I could change it to a fallback solution that goes back to `rm -rf`?!

**Comment by joekerna** [comment]
Or I could create the temporary empty directory using `mktemp -d`?! But is that available on all systems?!

**Comment by laurent22** [comment]
Yes I think `mktemp` should be reliable but indeed we need to check that the directory has been successfully created before running rsync on it. Otherwise if, for instance, it's set to an empty string or just `/` we might end up doing `rsync -a --delete / '$1'`.

And if the directory couldn't be created, then yes please default to `rm -rf`.

**Comment by joekerna** [comment]
I would create the temp-directory once for each run of the script (not within `fn_rm`). Then use it for all deletions in that particular run. Delete it (again outside of `fn_rm`) once at the end of the script.
I don't think it's very efficient to create a new temp-directory every time `fn_rm` is called.

Do we need a temp-directory anywhere else in the script?

**Comment by laurent22** [comment]
Calling `mkdir -p` is cheap normally (I'd assume a few ms) so I think it would be fine to put everything in fn_rm, that way we don't need to worry about managing and cleaning up global state outside the function.

If we needed the temp dir outside, yes that would make sense, but at the moment it's only needed in fn_rm.

**Comment by joekerna** [comment]
Sorry, I'm trying to get my fork up to date because 

> This branch is 4 commits ahead, 8 commits behind laurent22:master. 

How do I do that? I've been googling about rebase and what not but I can't get it done...

**Comment by laurent22** [comment]
Ok so now that we went back to using `rm` this issue can be closed too.
