### ISSUE TITLE
fn_rm not working over SSH

### ISSUE THREAD

**Issue by joekerna** [laurent22/rsync-time-backup#78]
Deleting directories over SSH is not working.
`if [[ -d $1 ]]; then` is only checking if the directory `$1` exists locally. When doing a backup over SSH it should check on the remote server.
I tried `fn_run_cmd "test -d $1"` but couldn't make it work.

What's happening now is, it's going to the `rm -f` option but since that doesn't use the `-r` option itself, directories are not deleted at all.

**Comment by SubZero1993** [comment]
I just added a "f" to "rm -r" so it is "rm -rf '$1'" which is located in function fn_rm().. which works fine for me over SSH.

**Comment by joekerna** [comment]
Yes but then the improvement from #71 is gone. And that is a significant speed gain.

`fn_run_cmd` should return the exit code from the command it executed. Then we could replace `if [[ -d $1 ]]; then` with `fn_run_cmd "test -d $1"` and check for the exit code if it's a directory or not.

**Comment by laurent22** [comment]
Actually, are we sure that rsync is faster than rm?

I've just done the following tests to delete 100,000 files and this is what I got:

```
$ time rsync -a --delete /tmp/empty/ bigdir/

real    0m20.644s
user    0m0.203s
sys     0m17.844s

$ time rm -rf bigdir/

real    0m15.610s
user    0m0.156s
sys     0m11.828s
```

with the files being generated like this: `seq 100000 | xargs touch`

So `rm` appears to be 25% faster or am I missing something? Unfortunately the article we were basing our decisions on didn't have a test for `rm` so I guess we missed that.

Unless there's some evidence that rsync is actually faster in some conditions, I would be keen to go back to using just `rm` as it is simpler and more reliable.

**Comment by joekerna** [comment]
You may be right. In this [article](https://stackoverflow.com/questions/1795370/unix-fast-remove-directory-for-cleaning-up-daily-builds) they also claim that `rm` is the fastest option.

And I would assume that whoever programmed such a simple command like `rm` in Linux decades ago, would have optimized it to the max by now.

**Comment by laurent22** [comment]
Ok that's good to know, then I'm going to change the script to use `rm` again.

**Comment by jurgihub** [comment]
@laurent22 Found a command that correctly rsync-deletes directories over SSH, and it's actually faster than rm -rf does over SSH:

rsync -r --delete --include '/2017-05-18-213048/***' --exclude='*' $(mktemp -d)/ user@server:/BackupDirectory/

Time results for the above command:

real	1m1.770s
user	0m0.414s
sys	0m1.691s

Time results for rm -rf (over SSH) on the same directory:

real	1m20.865s
user	0m0.023s
sys	0m0.008s

Might be worth considering using rsync again. Hope the above is somewhat useful.
