### ISSUE TITLE
how to use --copy-links

### ISSUE THREAD

**Issue by YannMoisan** [laurent22/rsync-time-backup#81]
Given that files/folders that I want to backup are in different locations, I'd like to create a folder `tobackup` that contains symlinks to all files/folders that must be backuped.

In that case, it seems that I must use `copy-links` instead of `links`.

Unfortunately, it seems that hard links from previous backup are deleted

```
├── bkp
│   ├── 2017-05-30-162857
│   ├── 2017-05-30-162912
│   ├── 2017-05-30-163014
│   │   ├── photos
│   │   │   └── img
│   │   └── videos
│   │       └── vid
│   ├── backup.marker
│   └── latest -> 2017-05-30-163014
```

Here is the command : 
```
rsync_tmbackup.sh --rsync-set-flags "-D --compress --numeric-ids --copy-links --hard-links --one-file-system --itemize-changes --times --recursive --perms --owner --group --stats --human-readable" tobackup bkp/
```

**Comment by joekerna** [comment]
Can the deletion of previous backups be related to #82?

**Comment by laurent22** [comment]
Yes, looks like it's the same issue. @YannMoisan, please could you give a try to the latest version (which should be fixed) and confirm if it's now working for you?
