### ISSUE TITLE
Section "add symlink to last backup" empties previous backup folder

### ISSUE THREAD

**Issue by jurgihub** [laurent22/rsync-time-backup#82]
Title is self-explanatory. On my Linux setup (Gentoo, rsync 3.1.2, local non-SSH backup), I noticed that all previous backup folders are empty (i.e. no history is being kept). When I comment out the line 

fn_rm "$DEST_FOLDER/latest"

, all is well again. Presumably, removing the "latest" link empties (not deletes) the folder it points to.

However, when backing up my MacBook (which backs up over SSH to the Gentoo box described above), the original script works as designed, and none of the backup folders are emptied.

**Comment by joekerna** [comment]
I can confirm that it's working on MacOS and it is also working as desired on Ubuntu 17.04. Is it a Gentoo specific problem?!

**Comment by laurent22** [comment]
Maybe we need to add a check to our new `fn_rm`? If it's a symlink, don't use rsync to delete, as that would recursively delete everything if the OS make the link look like a dir, while `rm` (without -r) will either fail or only delete the symlink.

**Comment by jurgihub** [comment]
The problem is for sure in fn_rm (as called at the end of the script to delete the "latest" symlink), and more specifically in:

fn_run_cmd "rsync -a --delete /tmp/rsync-time-backup-emptydir/ '$1'"

I've just run this manually -- rsync attempts to sync an empty folder (which we have created in /tmp) with the /latest symlink. Since latest is still linked to our previous backup folder, it simply empties that folder. I've just browsed through "man sync", and that's what --delete does: it deletes files on the destination folder, which in this case is "latest", which is linked to our previous backup folder.

Regardless, the script identifies "latest" as a directory, which is true. But it's also a symlink, which can be checked with -L.

Still don't know why it does seem to work on Ubuntu though.

**Comment by joekerna** [comment]
Then this is very much related to #78. We have to improve the way `fn_rm` determines if the given parameter is a directory or a file/link.

**Comment by joekerna** [comment]
Why it is working on Ubuntu and not on Gentoo is strange. What does `test -d latest; echo $?` return on Gentoo?

**Comment by laurent22** [comment]
According to [this](https://unix.stackexchange.com/questions/96907/how-do-i-check-if-a-file-is-a-symbolic-link-to-a-directory) `test -d` would return true even for a symlink. So I think we should change our test to check both for "dir and not symlink" with something like this (not tested yet):

```
fn_rm() {
	if [[ -d $1 && ! -L $1 ]]; then
		# when deleting a directory use rsync for performance reasons
		fn_run_cmd "mkdir -p /tmp/rsync-time-backup-emptydir"
		fn_run_cmd "rsync -a --delete /tmp/rsync-time-backup-emptydir/ '$1'"
		fn_run_cmd "rm -rf /tmp/rsync-time-backup-emptydir '$1'"
	else
		# when deleting a file use regular rm
		fn_run_cmd "rm -f '$1'"
	fi
}
```

**Comment by jurgihub** [comment]
I agree. Both checks are necessary.

@joekerna --> test -d latest returns 0 (on Gentoo). test -L latest returns 0 as well (on Gentoo). So it's a directory and a symlink. You've got other return codes on Ubuntu?

**Comment by joekerna** [comment]
I don't have Ubuntu here now. But I can confirm the same behavior on SuSE. I guess Ubuntu will behave the same. But I don't have the issue that my backups are emptied.

**Comment by joekerna** [comment]
I'm sorry, I have to **confirm** the issue on Ubuntu! Since I have a little history of my backups throughout May I can say that the issue started on May 11. Every backup until then including May 10th is still intact. Backup through SSH is working as intended, probably because the `fn_rm` using `rsync` is not working.

**Comment by jurgihub** [comment]
@joekerna Re your question about Mac backup over SSH --> I can't really say, because at one point I added "-f" to fn_rm, and I'm not sure how that may have impacted my backup results. I do remember that one point the script wouldn't expire old backups (which I think is why I added -f).

**Comment by jurgihub** [comment]
@laurent22 I've just tested the code you suggested above. Works for me! Previous backup directory is no longer being emptied. Can't tell how this impacts the "expire" function, since nothing needs expiring here at the moment.

**Comment by laurent22** [comment]
@jurgihub, I've integrated the changes we discussed in b41589ec778c858ca38a54b3f9745963b91f3d23 (I've now split the deletion methods so that the optimised one is only to expire backups). Please give it a try and confirm that it's working as expected.

**Comment by jurgihub** [comment]
Works perfect locally, but does not work over SSH, I'm afraid.

Going through the code, I guess this was to be expected since [[ -d $DIR && ! -L $DIR ]] tests from the perspective of the source, and the directory we want to expire is on the target. Therefore the above test will always be false, making us jump to the else clause, and that's why, over SSH, I always get the "Trying to delete..." error message.

In the "old" script, when fn_rm was used, even on SSH, it always went for "rm -rf" (for the same reason as explained above).

Maybe we should *always* go for "rm -rf" anyway.

**Comment by laurent22** [comment]
@jurgihub, I've reverted to always use `rm`. Please give it another try to see if it's working over SSH now.

**Comment by jurgihub** [comment]
@laurent22 Works like a charm!!

**Comment by laurent22** [comment]
Great, thanks for the confirmation!
