### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by Loki3000** [laurent22/rsync-time-backup#85]
1. It's going to be good to have the opportunity to send a backup report to specified email.
2. I think that it's to be usefull to control percent of backup delta. If delta more then some limit (for example, more then 40% of files has changed since last backup), it's mean that something goes wrong (for example-cryptolocker) and alert mail will be reasonable.

**Comment by laurent22** [comment]
Unfortunately I think that would be out of scope for this project.

Sending the log by email should be relatively straightforward with a custom script (use the `--log-dir` to specify first where the log should go, then email them).

The second one would be tricky as I don't think rsync reports such a percentage. It might be possible to do it in a custom solution though, based on the log file size (i.e. if over x MB, send an email).

**Comment by Loki3000** [comment]
I invented the following method:
rate = (size of file without hardlinks in "latest" folder) / (tatal "latest" folder size)
works well for changed files.
