### ISSUE TITLE
Large file system

### ISSUE THREAD

**Issue by aureliobalgera** [laurent22/rsync-time-backup#87]
In large file system I'm experiencing strange error 

like

rsync_tmbackup: rsync -D --compress --numeric-ids --links --hard-links --one-file-system --itemize-changes --times --recursive --perms --owner --group --stats --human-readable --log-file '/root/.rsync_tmbackup/2017-09-04-222524.log' --link-dest='/media/mulgamma/2017-09-03-220001' -- '/mnt/' '/media/mulgamma/2017-09-04-220002/'
rsync: link_stat "/mnt/." failed: Connection reset by peer (104)

like

rsync_tmbackup: Previous backup found - doing incremental backup from /media/mulgamma/2017-09-05-220001
rsync_tmbackup: Creating destination /media/mulgamma/2017-09-06-220001
rsync_tmbackup: Expiring /media/mulgamma/2017-08-05-220002
rsync_tmbackup: Starting backup...
rsync_tmbackup: From: /mnt/
rsync_tmbackup: To:   /media/mulgamma/2017-09-06-220001/
rsync_tmbackup: Running command:
rsync_tmbackup: rsync -D --compress --numeric-ids --links --hard-links --one-file-system --itemize-changes --times --recursive --perms --owner --group --stats --human-readable --log-file '/root/.rsync_tmbackup/2017-09-06-221843.log' --link-dest='/media/mulgamma/2017-09-05-220001' -- '/mnt/' '/media/mulgamma/2017-09-06-220001/'
rsync: link_stat "/mnt/." failed: Host is down (112)

only after 20 day of absolutely regular running. 

failed: Connection reset by peer (104)
failed: Host is down (112)

are not true... Wath's happening??

**Comment by aureliobalgera** [comment]
But only if I run the scritps batch. If I run the same script interactively everything goes well..... But the first 20  days no problem at all in batch too

**Comment by laurent22** [comment]
Looks like a server error rather than an issue with script
