### ISSUE TITLE
How to restore

### ISSUE THREAD

**Issue by wsokc** [laurent22/rsync-time-backup#88]
Hi Laurent,

I managed to meet up the situation where I need to restore.
Would you share please how to do this according to the scripts ?

Cheers,
Raff

**Comment by laurent22** [comment]
Hi Raff, the script creates a backup in a regular directory so you can simply copy the files back to the original directory. You would do that with something like `rsync -aP /path/to/last/backup/ /path/to/restore/to/`

**Comment by laurent22** [comment]
I've added a section about this in the README file 1ed730e61451133b6fd52b1ef3ff672ffb166d6a
