### ISSUE TITLE
Error with symlink to folder

### ISSUE THREAD

**Issue by Loki3000** [laurent22/rsync-time-backup#92]
Following case:
```
/path/to/backup <--backup folder
/backup <-- symlink to /path/to/backup
```
make buckup:
```
rtbackup /some/path/ /backup/
```
make another backup:
```
#expecting incremental backup
rtbackup /some/path/ /backup/
#as a result - new full backup
```
the reason is here
https://github.com/laurent22/rsync-time-backup/blob/master/rsync_tmbackup.sh#L205
and here
https://github.com/laurent22/rsync-time-backup/blob/master/rsync_tmbackup.sh#L63

```
find "/backup" -maxdepth 1 -type d //returns empty
find "/backup/" -maxdepth 1 -type d //returns list of dirs
```

**Comment by laurent22** [comment]
Right, that's indeed a problem. However, since we know that the destination and source don't have a / at the end (it's stripped off) I guess we could simply add it just when running the `find` command.

**Comment by Loki3000** [comment]
I'm already added it in my own copy. As I can see it's works well.
