### ISSUE TITLE
Question: multiple source directories

### ISSUE THREAD

**Issue by alxgarza** [laurent22/rsync-time-backup#94]
How do you add multiple source directories?

**Comment by laurent22** [comment]
There's no built-in way to do this, although it's relatively easy to call the command multiple times with different source directory (for example from a bash file).

**Comment by alxgarza** [comment]
Thank's

**Comment by joekerna** [comment]
Or you can use the rsync exclude mechanism and backup the next common directory. Then you just exclude everything that you don't want.

**Comment by alxgarza** [comment]
The problem that I've found when calling rsync-time-backup multiple times with different source is that you get a different timestamp directory for each call.

**Comment by luckydonald** [comment]
Might be possible to symlink multiple folders into a parent folder, and back up that one.
Otherwise instead of symlinks, via mounts.

**Comment by Wikinaut** [comment]
I tried it via symbolic links, but this did not work. Only the symbolic links are then in the backup, not followed to the targets.

**Comment by trompx** [comment]
Hey @Wikinaut could you update on the eventual side-effects you encountered while using the `--copy-links`?
@laurent22 are nested mounted points supported by default?
Instead of symlink, I plan to mount partitions under the same arbo to have a single backup:
```
/			(Disk 1 partition 1)
	/home		(Mountpoint 1 or Disk 1 partition 2)
		/aaa
		/data	(Mountpoint 2 or Mountpoint 1)
```
And thanks for the script by the way!

**Comment by elbowz** [comment]
Same issue...

I have to backup a site:
* DocumentRoot/htdocs
* db-sql-dump.tar.gz

is there some best practice to do that?
