### ISSUE TITLE
Compression after backup -request

### ISSUE THREAD

**Issue by thefiredragon** [laurent22/rsync-time-backup#98]
Your backup script is working fine, but here I would have a litte request, could it possible to bring a also a compression to tar.gz or gz? 
This would be really fine. 
best Regards,
Dan

**Comment by psmanek** [comment]
This doesn't make sense. The script is comparing previous backup with actual data. So it is impossible to compare if data is compressed without uncompressed it.

**Comment by thefiredragon** [comment]
Okay, I understand so it would not be make sense and break the comparing feature.
But thanks for your fast answer here, :)
